# Generated by Django 4.0.2 on 2022-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('description', models.TextField(default='This is a description for <django.db.models.fields.CharField>')),
                ('category', models.CharField(default='general', max_length=200)),
            ],
        ),
    ]
