# Generated by Django 4.0.2 on 2022-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydata',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='everydata',
            name='description',
            field=models.TextField(),
        ),
    ]
