# Generated by Django 4.0.2 on 2022-03-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0003_alter_everydata_category_alter_everydata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydata',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
