# Generated by Django 4.0.2 on 2022-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0005_searchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
